[tool.poetry]
name = "hier-config-gpt"
version = "0.1.0"
description = "\"An enhanced Hierarchical Configuration library that integrates GPT capabilities for advanced configuration analysis and remediation.\""
authors = ["James Williams <james.williams@packetgeek.net>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic = "^2.9.2"
hier-config = "^3.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-cov = "^6.0.0"
ruff = "^0.7.4"
mypy = "^1.13.0"
pylint = "^3.3.1"
mkdocs = "^1.6.1"


[tool.poetry.group.chatgpt.dependencies]
openai = "^1.54.4"


[tool.poetry.group.anthropic.dependencies]
anthropic = "^0.39.0"


[tool.poetry.group.ollama.dependencies]
ollama = "^0.4.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
